name: CD-pipeline

on:
  workflow_run:
    workflows: ["CI-pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Pull Docker image
      run: sudo docker pull thaile1809/cicd-practice:latest 
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container
